# Generated by Django 2.2.8 on 2025-10-17 06:07

from django.db import migrations, models


def remove_field_if_exists(apps, schema_editor):
    """Safely remove the field only if it exists in the database."""
    with schema_editor.connection.cursor() as cursor:
        # Check if the column exists in PostgreSQL
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 
                FROM information_schema.columns 
                WHERE table_schema = 'public'
                AND table_name='backend_product' 
                AND column_name='only_on_default_color'
            );
        """)
        column_exists = cursor.fetchone()[0]
        
        if column_exists:
            # Column exists, remove it
            cursor.execute("ALTER TABLE backend_product DROP COLUMN only_on_default_color;")


def reverse_operation(apps, schema_editor):
    """Re-add the field if needed (for reverse migration)."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 
                FROM information_schema.columns 
                WHERE table_schema = 'public'
                AND table_name='backend_product' 
                AND column_name='only_on_default_color'
            );
        """)
        column_exists = cursor.fetchone()[0]
        
        if not column_exists:
            cursor.execute("ALTER TABLE backend_product ADD COLUMN only_on_default_color BOOLEAN DEFAULT TRUE;")


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20210724_2304'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='product',
                    name='only_on_default_color',
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    remove_field_if_exists,
                    reverse_operation,
                ),
            ],
        ),
    ]

