# Generated by Django 2.2.8 on 2025-11-04 07:43

from django.db import migrations, models


def remove_field_if_exists(apps, schema_editor):
    """Safely remove the product_color_default field only if it exists in the database."""
    with schema_editor.connection.cursor() as cursor:
        # Check if the column exists in PostgreSQL
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 
                FROM information_schema.columns 
                WHERE table_schema = 'public'
                AND table_name='backend_product' 
                AND column_name='product_color_default_id'
            );
        """)
        column_exists = cursor.fetchone()[0]
        
        if column_exists:
            # Column exists, remove it
            cursor.execute("ALTER TABLE backend_product DROP COLUMN product_color_default_id;")
            print("Removed product_color_default_id column")
        else:
            print("product_color_default_id column does not exist, skipping removal")


def reverse_operation(apps, schema_editor):
    """Re-add the field if needed (for reverse migration)."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 
                FROM information_schema.columns 
                WHERE table_schema = 'public'
                AND table_name='backend_product' 
                AND column_name='product_color_default_id'
            );
        """)
        column_exists = cursor.fetchone()[0]
        
        if not column_exists:
            # Check if ProductColor table exists
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1 
                    FROM information_schema.tables 
                    WHERE table_schema = 'public'
                    AND table_name='backend_productcolor'
                );
            """)
            table_exists = cursor.fetchone()[0]
            
            if table_exists:
                cursor.execute("""
                    ALTER TABLE backend_product 
                    ADD COLUMN product_color_default_id INTEGER NULL 
                    REFERENCES backend_productcolor(id) ON DELETE SET NULL;
                """)
                print("Re-added product_color_default_id column")


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_remove_product_only_on_default_color'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='product',
                    name='product_color_default',
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    remove_field_if_exists,
                    reverse_operation,
                ),
            ],
        ),
    ]

